### ISSUE TITLE
iOS : ** BUILD FAILED ** with SDK 8.0.GA

### ISSUE THREAD

**Issue by nicolomonili** [Pushwoosh/pushwoosh-appcelerator-titanium#63] opened 2019-03-15 11:04 UTC
Tested with versions **5.8.0** and **5.12.0** of the module
With Titanium SDK **8.0.GA** the build failed, with **7.5.1.GA** it's ok.
```
[TRACE] :  Ld /Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Products/Debug-iphonesimulator/******.app/****** normal x86_64 (in target: *****)
[TRACE] :      cd /Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone
[TRACE] :      export IPHONEOS_DEPLOYMENT_TARGET=9.0
[TRACE] :      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -L/Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Products/Debug-iphonesimulator -L/Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/lib -L/Users/******/Library/Application\ Support/Titanium/modules/iphone/ti.map/3.1.0 -L/Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/modules/iphone/com.pushwoosh.module/5.12.0 -F/Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Products/Debug-iphonesimulator -FFrameworks -filelist /Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Intermediates/******.build/Debug-iphonesimulator/******.build/Objects-normal/x86_64/******.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Intermediates/******.build/Debug-iphonesimulator/******.build/Objects-normal/x86_64/******_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib=libc++ -fobjc-link-runtime -ObjC -weak_framework JavaScriptCore -weak_framework MapKit -weak_framework MapKit -lxml2 -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Intermediates/******.build/Debug-iphonesimulator/******.build/******.app-Simulated.xcent -framework CoreMedia -weak_framework CoreMotion -weak_framework CoreText -framework EventKit -framework EventKitUI -weak_framework Security -framework Foundation -weak_framework UIKit -framework CoreGraphics -weak_framework AddressBook -framework AddressBookUI -framework CFNetwork -framework CoreLocation -weak_framework MapKit -framework MessageUI -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework AudioToolbox -weak_framework MediaPlayer -framework AVFoundation -ltiverify -lti.map -lcom.pushwoosh.module -framework TitaniumKit -Xlinker -dependency_info -Xlinker /Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Intermediates/******.build/Debug-iphonesimulator/******.build/Objects-normal/x86_64/******_dependency_info.dat -o /Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Products/Debug-iphonesimulator/******.app/******
[TRACE] :  Undefined symbols for architecture x86_64:
[TRACE] :    "_deflate", referenced from:
[TRACE] :        pushwoosh::zipWriteInFileInZip(void*, void const*, unsigned int) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :        pushwoosh::zipCloseFileInZipRaw(void*, unsigned long, unsigned long) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :    "_inflate", referenced from:
[TRACE] :        pushwoosh::unzReadCurrentFile(void*, void*, unsigned int) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :    "_deflateInit2_", referenced from:
[TRACE] :        pushwoosh::zipOpenNewFileInZip3(void*, char const*, pushwoosh::zip_fileinfo const*, void const*, unsigned int, void const*, unsigned int, char const*, int, int, int, int, int, int, char const*, unsigned long) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :    "_inflateEnd", referenced from:
[TRACE] :        pushwoosh::unzCloseCurrentFile(void*) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :    "_crc32", referenced from:
[TRACE] :        pushwoosh::unzReadCurrentFile(void*, void*, unsigned int) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :        -[PWZipArchive addFileToZip:newname:] in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :        pushwoosh::zipWriteInFileInZip(void*, void const*, unsigned int) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :    "_deflateEnd", referenced from:
[TRACE] :        pushwoosh::zipCloseFileInZipRaw(void*, unsigned long, unsigned long) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :    "_inflateInit2_", referenced from:
[TRACE] :        pushwoosh::unzOpenCurrentFile3(void*, int*, int*, int, char const*) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE] :  ld: symbol(s) not found for architecture x86_64
[TRACE] :  clang: error: 
[TRACE] :  linker command failed with exit code 1 (use -v to see invocation)
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld /Users/******/Desktop/Appcelerator\ Workspace/1\ -\ ******/build/iphone/build/Products/Debug-iphonesimulator/******.app/****** normal x86_64
[ERROR] :  (1 failure)
```

**Comment by wfhm** [comment] 2019-03-15 11:18
Hi @nicolomonili ,

Checking it.

**Comment by nicolomonili** [comment] 2019-03-18 20:41
Is the problem confirmed?

**Comment by wfhm** [comment] 2019-03-19 10:02
@nicolomonili We could not reproduce the build error, however the investigation is not over yet. I will provide you with a status update once there is any.

**Comment by rlustemberg** [comment] 2019-03-20 20:52
Have same issue. It cannot resolve methods on the included frameworks. I've seen it on other modules.

**Comment by wfhm** [comment] 2019-03-21 07:55
@nicolomonili @rlustemberg fixed with the latest release.

**Closed as completed by wfhm** 2019-03-21 07:55 UTC
