### ISSUE TITLE
Module doesn't work on android with map

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [Pushwoosh/pushwoosh-appcelerator-titanium#35] opened 2016-11-21 13:02 UTC
[ERROR] Failed to run dexer:
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ErrorDialogFragment;
[ERROR]         at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR]         at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR]         at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR]         at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR]         at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR]         at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR]         at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzrn;
[ERROR]         at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR]         at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR]         at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR]         at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR]         at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR]         at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR]         at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/iid/zzc;
[ERROR]         at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR]         at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR]         at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR]         at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR]         at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR]         at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR]         at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR] 3 errors; aborting

**Comment by wfhm** [comment] 2016-11-22 11:29
Hi,

Looks like there is another lib in your project containing google-play-services. Could you please check?

**Comment by MahmoudElmoghazy** [comment] 2016-11-23 15:09
I updated my map to the the version of the push woosh and remove and lib from the module unless the Pushwoosh.jar

**Comment by macasfaj** [comment] 2016-11-26 19:04
Did you fix that? What version of Ti.map are you using?

**Comment by juanagu** [comment] 2016-12-22 14:13
Hello! I have the same issue, I use Pushwoosh 3.0.0, Ti.Map 3.1.0 and SDK 6.0. Any solution?

**Comment by viridanti** [comment] 2017-02-08 11:29
Hi,

The root cause of this issue is a conflict between different plugins containing play services libs, it occurs when you use more than one plugin with the lib. For more info please refer to the following documentation:

http://docs.pushwoosh.com/docs/resolving-google-play-services-conflicts#2-unity-appcelerator-titanium

**Comment by safadig** [comment] 2017-02-08 11:35
True, but it is very common as many apps use Ti.map

**Comment by perdona** [comment] 2017-03-08 22:44
This is so frustrating. Still nothing on this issue?

**Comment by perdona** [comment] 2017-03-09 18:34
@viridanti the docs don't show any resolution. For those who PAY for pushwoosh, don't u guys think it's time to solve this? Release a version for using along with ti.map, without the conflicting classes...

**Comment by wfhm** [comment] 2017-03-10 14:43
You can find conflicting libs in the following directory:

https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/tree/master/Push-Notifications-Module/modules/android/com.pushwoosh.module/3.0.0/lib

Please try [this solution](https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/issues/35#issuecomment-262540138) offered by @MahmoudElmoghazy. Just check which plugin requires a higher version of google-play-services and leave this version in your app.

**Comment by perdona** [comment] 2017-03-10 18:28
@wfhm thanks for the feedback, but where do I find the complete google-play-services.jar ? When I leave only the ti.map jars, my app crashes due to libraries missing from the pushwoosh jars I deleted.
When I delete ti.map jars, the app crashes due to missing libs on map jars I deleted.

**Comment by perdona** [comment] 2017-03-10 22:31
Guys, finally made it work.
In my case, I removed all pushwoosh JARs and copied, in the /lib folder along with pushwoosh.jar, google-play-services-gcm.jar and google-play-services-iid.jar from NATIVE ti.cloudpush /lib folder.

**Comment by csemrm** [comment] 2017-10-15 06:46
Hello @vveysner , 

Anyone facing Ti.map and pushwoosh android module in Ti SDK 6.2.2GA? 

Please share your workaround for latest Ti SDK and pushwoosh module in Android platform. 

Thanks

**Comment by wfhm** [comment] 2017-10-16 10:38
@csemrm 

You can find the google-play-services libs in Pushwoosh plugin:
https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/tree/master/Push-Notifications-Module/modules/android/com.pushwoosh.module/3.4.0/lib

Ti.Map uses the same libs, but of another versions:

https://github.com/appcelerator-modules/ti.map/tree/master/android/lib

Just update, change or remove it either for Pushwoosh module or for Ti.Map to have just one instance of this lib in your project. Please note that Pushwoosh module requires 11.+ version of google-play-services to function.

**Comment by csemrm** [comment] 2017-10-20 16:30
@wfhm I tried several ways. But still no success.  Do you have any demo code with Ti.MAP and Pushwoosh modules? 

Thanks

**Comment by perdona** [comment] 2017-10-20 16:52
Following this cause I had the same issue every time I need to update Titanium SDK.
Sharing @wfhm struggle, we hope you can provide us with a workaround, because this is very frustrating... Thanks in advance!

**Comment by beaur** [comment] 2017-10-24 02:58
Also facing issues with this module and google play services and none of my usual tricks I've used in the past are working.  It would be great to have some versions that worked with other common modules that cause conflicts eg. ti-ga (google analytics) and ti.map.  I have a conflict with ti-ga myself.

**Comment by wfhm** [comment] 2017-12-14 06:30
@MahmoudElmoghazy to fix this issue we need the latest version of Titanium, which currently is in beta. Once it is release we will roll the fix out.

**Comment by safadig** [comment] 2017-12-14 11:22
I thought Titanium 7.0 GA addressed this issue specifically. Its already out, not in beta?
[https://www.appcelerator.com/blog/2017/12/ga-release-of-titanium-sdk-7-0-0-hyperloop-cli-7-0-0-appcelerator-studio-5-0-0/](url)

**Comment by wfhm** [comment] 2017-12-21 11:02
@safadig @MahmoudElmoghazy fixed in 5.5.2 version. You should also update your Titanium SDK to the latest one.

**Closed as completed by wfhm** 2017-12-21 11:02 UTC
