### ISSUE TITLE
ios: EXC_BAD_ACCESS dynamicDidRegisterForRemoteNotificationsWithDeviceToken responds to selector

### ISSUE THREAD

**Issue by TylerZubke** [Pushwoosh/pushwoosh-appcelerator-titanium#62] opened 2019-02-12 23:31 UTC
I just wanted to leave this here in case anybody else runs into the same issue. Our iOS app started crashing right after launch with this error. I finally stumbled across the exact same issue in the Pushwoosh Unity plugin repo (https://github.com/Pushwoosh/pushwoosh-unity/issues/31). The important part of that issue is in an image so it doesn't come up in most google searches. The solution seems to be to initialize Pushwoosh and call registerForPushNotifications() BEFORE initializing Firebase.

**Comment by wfhm** [comment] 2019-02-18 11:25
@TylerZubke  could you please specify Pushwoosh module version as well as the name and the version of another library using Firebase?

**Comment by wfhm** [comment] 2019-02-28 09:39
@TylerZubke any updates?

**Comment by TylerZubke** [comment] 2019-02-28 19:48
Sorry, this was with 5.8.0. I saw a new version was released, but I haven't tested our old code with this new version to see if it still crashes. I'm not sure what you mean by "...name and the version of another library using Firebase". We're using version 5.5.0 of Firebase and the same version for Firebase Analytics. We just add these to the project using Cocoapods.

**Comment by wfhm** [comment] 2019-03-22 13:15
@TylerZubke we've checked the Titanium plugin with Firebase SDK v5.5.0, and we could not reproduce the issue. It actually should not even appear there - the Firebase-Pushwoosh conflict was resolved in 5.6.0 version of Pushwoosh SDK, while Pushwoosh Titanium plugin 5.8.0 uses 5.8.3 SDK version.  If the issue still persists, please send us a reproducer build, ideally, with the source code.

**Comment by wfhm** [comment] 2019-04-04 11:56
@TylerZubke any news?

**Closed as completed** 2019-04-08 09:37 UTC
