### ISSUE TITLE
Titanium SDK 9.2.2GA - no such table: lockScreenRemoteUrls

### ISSUE THREAD

**Issue by macasfaj** [Pushwoosh/pushwoosh-appcelerator-titanium#82] opened 2021-01-11 13:45 UTC
When I receive a notification on Android and I click it I get this issue. The App is frozen after that. Please, any help? 

Thanks!

`INFO]   Pushwoosh: | Url: https://CDCFE-20872.api.pushwoosh.com/json/1.3/pushStat

[INFO]   Pushwoosh: | Response: {"status_code":200,"status_message":"OK","response":null}

[INFO]   Pushwoosh: x

[INFO]   InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus

[ERROR]  SQLiteLog: (1) no such table: lockScreenRemoteUrls

[ERROR]  Pushwoosh: Can't get cached resources:

[ERROR]  Pushwoosh: android.database.sqlite.SQLiteException: no such table: lockScreenRemoteUrls (code 1): , while compiling: SELECT * FROM lockScreenRemoteUrls

[ERROR]  Pushwoosh: #################################################################

[ERROR]  Pushwoosh: Error Code : 1 (SQLITE_ERROR)

[ERROR]  Pushwoosh: Caused By : SQL(query) error or missing database.

[ERROR]  Pushwoosh: (no such table: lockScreenRemoteUrls (code 1): , while compiling: SELECT * FROM lockScreenRemoteUrls)

[ERROR]  Pushwoosh: #################################################################

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1096)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:661)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1746)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1593)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1464)

[ERROR]  Pushwoosh: at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1632)

[ERROR]  Pushwoosh: at com.pushwoosh.repository.LockScreenMediaStorageImpl.d(Unknown Source:21)

[ERROR]  Pushwoosh: at com.pushwoosh.internal.utils.LockScreenReceiver$c.a(Unknown Source:4)

[ERROR]  Pushwoosh: at com.pushwoosh.internal.utils.LockScreenReceiver$c.doInBackground(Unknown Source:2)

[ERROR]  Pushwoosh: at android.os.AsyncTask$2.call(AsyncTask.java:333)

[ERROR]  Pushwoosh: at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[ERROR]  Pushwoosh: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)

[ERROR]  Pushwoosh: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

[ERROR]  Pushwoosh: at java.lang.Thread.run(Thread.java:764)`

**Comment by wfhm** [comment] 2021-01-12 13:49
@macasfaj,

Will be fixed with the next release.

**Comment by macasfaj** [comment] 2021-01-12 13:58
Thank you @wfhm 

This issue is blocking us, we heavily depend on push notification marketing and platform vibrancy. Please, we need it to be fixed urgently or we will have to move to another platform.

Regards.

**Comment by wfhm** [comment] 2021-01-27 10:56
@macasfaj,

Sorry for the delayed response! The issue is fixed in our native Android SDK, so we just need to update the module to fix it in Titanium. This will be done right after we release a new version of the iOS SDK (expected to be done by the end of this week). The Titanium module will be updated early next week.

**Comment by wfhm** [comment] 2021-02-11 08:58
@macasfaj,

Fixed with 6.0.1.

**Comment by macasfaj** [comment] 2021-02-11 08:59
Thanks!!!!!

**Closed as completed by wfhm** 2021-02-11 08:58 UTC
Labels: 56532
